### PR TITLE
Feature/0.1.0 beta.rro13 b/consultar becas mike

### PR DESCRIPTION
**Pull request by Bromaeg**
Cambios en getschollarships para obtener todos los datos y no tener focus, devuelve toda la imagen

### CODE REVIEW

**Review by A01352033 — CHANGES_REQUESTED** [review]
Why you erased the filter?? I suggest you to keep working on that instead of just calling all the objects. It would be better if there are a lot of objects and you want to look for one of 'em.

**Comment by Bromaeg** [comment]
I deleted the filters because the difference between the general view and the detailed one its almost none, they're showing almost the same information as the detailed info, so the front-end (iOS I believe) developers asked me to change it, it wasn't my will.

So the solution is to call all the objects one by one with my previous filters than just call all the objects?, because as I said, the difference between the detailed view and general view its almost none existant, the main difference scholarships end date.

**Comment by A01352033** [comment]
> I deleted the filters because the difference between the general view and the detailed one its almost none, they're showing almost the same information as the detailed info, so the front-end (iOS I believe) developers asked me to change it, it wasn't my will.
> 
> So the solution is to call all the objects one by one with my previous filters than just call all the objects?, because as I said, the difference between the detailed view and general view its almost none existant, the main difference scholarships end date.

Sounds good for me, enjoy your pr mike!! :)

**Review by A01352033 — APPROVED** [review]
LGTM

**Review by itschavaa — APPROVED** [review]

**Pull request merged**
